name: Unity WebGL Build

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print placeholder
        run: echo "This is a placeholder workflow for main branch."
